from __future__ import annotations

VALID_ENTITY_TYPES = {
    "Person",
    "Organization",
    "Technology",
    "Concept",
    "System",
    "Module",
    "Package",
    "File",
    "Class",
    "Function",
    "APIEndpoint",
    "DataModel",
    "Database",
    "DataStore",
    "Queue",
    "ExternalService",
    "DeploymentUnit",
    "Environment",
    "Config",
    "SecretRef",
    "Workflow",
    "UserRole",
    "Decision",
    "Requirement",
    "Issue",
    "Task",
    "BusinessEntity",
}

VALID_PREDICATES = {"mentions", "related_to", "blocks", "requires", "decides", "uses"}

CANONICAL_PREDICATES = {
    "mentions",
    "related_to",
    "relates_to_domain",
    "blocks",
    "requires",
    "decides",
    "uses",
    "implements",
    "supports",
    "depends_on",
    "generates",
    "stores",
    "classifies",
    "documents",
    "configures",
    "runs_on",
    "exports",
    "owned_by",
    "manages",
    "enriches",
    "discovers",
    "creates",
    "validates",
    "syncs",
    "contains",
    "produces",
    "reads_from",
    "writes_to",
    "calls",
    "imports",
    "imports_from",
    "defines",
    "exposes",
    "handles",
    "deploys_to",
    "evidences",
    "part_of",
    "references",
    "inherits",
    "rationale_for",
    "shares_data_with",
    "method",
    "reports_to",
    "member_of",
    "has_role",
    "has_skill",
    "located_in",
    "filed_by",
    "covered_by",
    "has_document",
    "evaluated_by",
    "triggered_rule",
    "resulted_in",
    "handled_by",
    "approved_by",
    "rejected_by",
    "paid_to",
}

PREDICATE_ALIASES = {
    "is_required_for": "requires",
    "required_for": "requires",
    "needs": "requires",
    "built_with": "uses",
    "powered_by": "uses",
    "uses_for": "uses",
    "create": "generates",
    "creates": "generates",
    "produces": "generates",
    "outputs": "exports",
    "export": "exports",
    "backs": "supports",
    "backed_by": "supports",
    "depends": "depends_on",
    "depends on": "depends_on",
    "owned by": "owned_by",
    "owned-by": "owned_by",
    "runs on": "runs_on",
    "runs-on": "runs_on",
    "configured_by": "configures",
    "documented_by": "documents",
    "related": "related_to",
    "call": "calls",
    "called_by": "calls",
    "import": "imports",
    "imported_from": "imports_from",
    "defined_by": "defines",
    "expose": "exposes",
    "served_by": "handles",
    "deployed_to": "deploys_to",
    "evidence": "evidences",
    "part of": "part_of",
    "part-of": "part_of",
}

VALID_PREDICATES = CANONICAL_PREDICATES


def normalize_predicate(predicate: str) -> str:
    normalized = predicate.strip().lower().replace("-", "_").replace(" ", "_")
    return PREDICATE_ALIASES.get(normalized, normalized)
